lanes:
- from: 수-1
  to: 수면실
  bidirectional: true
- from: 수면실
  to: 수-2
  bidirectional: true
- from: 수-3
  to: 수-4
  bidirectional: true
- from: 수-4
  to: 수-5
  bidirectional: true
- from: 수-1
  to: 수-3
  bidirectional: true
- from: 수면실
  to: 수-4
  bidirectional: true
- from: 수-2
  to: 수-5
  bidirectional: true
- from: 놀-상-회
  to: 놀이방
  bidirectional: true
- from: 놀이방
  to: 놀-1
  bidirectional: true
- from: 놀-5
  to: 놀-6
  bidirectional: true
- from: 복도
  to: 복-1
  bidirectional: true
- from: 복-1
  to: 복-2
  bidirectional: true
- from: 복-2
  to: 복-3
  bidirectional: true
- from: 복-3
  to: 복-4
  bidirectional: true
- from: 복-4
  to: 복-5
  bidirectional: true
- from: 복-6
  to: 충전소입구
  bidirectional: true
- from: 출입구
  to: 복도입구
  bidirectional: true
- from: 복도입구
  to: 복도
  bidirectional: true
- from: 충전소입구
  to: 충전소
  bidirectional: true
- from: 놀-7
  to: 놀이방입구-하
  bidirectional: true
- from: 놀이방입구-하
  to: 복-1
  bidirectional: true
- from: 복-5
  to: 복-6
  bidirectional: true
- from: 놀-5
  to: 놀-4
  bidirectional: true
- from: 놀-4
  to: 놀-3
  bidirectional: true
- from: 놀-3
  to: 놀이방
  bidirectional: true
- from: 복-1
  to: 복-2-1
  bidirectional: true
- from: 복-2-1
  to: 복-2
  bidirectional: true
- from: 복-3-1
  to: 복-2-1
  bidirectional: true
- from: 복-4
  to: 복-4-1
  bidirectional: true
- from: 복-4-1
  to: 복-5
  bidirectional: true
- from: 복-4-1
  to: 복-3-1
  bidirectional: true
- from: 복-3
  to: 복-3-1
  bidirectional: true
- from: 놀-하-회
  to: 놀-5
  bidirectional: true
- from: 수-5
  to: 수면실입구
  bidirectional: true
- from: 놀-1
  to: 놀이방입구-상
  bidirectional: true
- from: 놀-6
  to: 놀-7
  bidirectional: true
- from: 수-회
  to: 수-3
  bidirectional: true
- from: 수면실입구
  to: 복-6
  bidirectional: true
- from: 놀이방입구-상
  to: 복-5
  bidirectional: true
