lanes:
- from: 수면실2
  to: 수면실
  bidirectional: true
- from: 수면실
  to: 수면실3
  bidirectional: true
- from: 수면실4
  to: 수면실5
  bidirectional: true
- from: 수면실5
  to: 수면실6
  bidirectional: true
- from: 수면실6
  to: 수면실7
  bidirectional: true
- from: 수면실2
  to: 수면실4
  bidirectional: true
- from: 수면실
  to: 수면실5
  bidirectional: true
- from: 수면실3
  to: 수면실6
  bidirectional: true
- from: 놀이방2
  to: 놀이방
  bidirectional: true
- from: 놀이방
  to: 놀이방3
  bidirectional: true
- from: 놀이방3
  to: 놀이방4
  bidirectional: true
- from: 놀이방5
  to: 놀이방6
  bidirectional: true
- from: 놀이방6
  to: 놀이방7
  bidirectional: true
- from: 복도
  to: 복도2
  bidirectional: true
- from: 복도2
  to: 복도3
  bidirectional: true
- from: 복도3
  to: 복도4
  bidirectional: true
- from: 복도4
  to: 복도5
  bidirectional: true
- from: 복도5
  to: 복도6
  bidirectional: true
- from: 복도7
  to: 충전소입구
  bidirectional: true
- from: 출입구
  to: 출입구2
  bidirectional: true
- from: 출입구2
  to: 복도
  bidirectional: true
- from: 출입구
  to: 운동장입구
  bidirectional: true
- from: 운동장입구
  to: 운동장3
  bidirectional: true
- from: 놀이방입구_하2
  to: 놀이방7
  bidirectional: true
- from: 수면실입구2
  to: 수면실7
  bidirectional: true
- from: 놀이방입구_상
  to: 복도6
  bidirectional: true
- from: 운동장3
  to: 운동장2
  bidirectional: true
- from: 운동장2
  to: 운동장
  bidirectional: true
- from: 충전소입구
  to: 충전소
  bidirectional: true
- from: 수면실입구2
  to: 수면실입구
  bidirectional: true
- from: 수면실입구
  to: 복도7
  bidirectional: true
- from: 놀이방입구_하2
  to: 놀이방입구_하
  bidirectional: true
- from: 놀이방입구_하
  to: 복도2
  bidirectional: true
- from: 놀이방4
  to: 놀이방입구_상2
  bidirectional: true
- from: 놀이방입구_상2
  to: 놀이방입구_상
  bidirectional: true
- from: 복도6
  to: 복도7
  bidirectional: true
- from: 놀이방5
  to: qwe1
  bidirectional: true
- from: qwe1
  to: qwe
  bidirectional: true
- from: qwe
  to: 놀이방
  bidirectional: true
